version: '3.8'

services:
  license-api:
    build: .
    container_name: smbeautyengine-license-api
    ports:
      - "1880:1880"
      - "2443:2443"
    environment:
      - ENABLE_HTTPS=true
      - SSL_CERT_PATH=/app/certs/cert.pem
      - SSL_KEY_PATH=/app/certs/key.pem
      - HTTP_PORT=1880
      - HTTPS_PORT=2443
      - LICENSE_DIR=/app/licenses
      - PRIVATE_KEY_PATH=/app/keys/private_key.pem
      - PUBLIC_KEY_PATH=/app/keys/public_key.pem
      - LICENSE_VALIDITY_DAYS=365
      - LOG_LEVEL=info
      - DOWNLOAD_BASE_URL=https://localhost:2443
    volumes:
      - license_data:/app/licenses
      - key_data:/app/keys
      - cert_data:/app/certs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--no-check-certificate", "https://localhost:2443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - license-network

  # 可选：添加 Redis 缓存支持
  # redis:
  #   image: redis:7-alpine
  #   container_name: license-api-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - license-network

  # 可选：添加 Nginx 反向代理
  # nginx:
  #   image: nginx:alpine
  #   container_name: license-api-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - license-api
  #   restart: unless-stopped
  #   networks:
  #     - license-network

volumes:
  license_data:
    driver: local
  key_data:
    driver: local
  cert_data:
    driver: local
  # redis_data:
  #   driver: local

networks:
  license-network:
    driver: bridge 