/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstant {

  /**
   * Full percent.
   */
  static readonly FULL_PERCENT = '100%';

  /**
   * Font weight 500.
   */
  static readonly FONT_WEIGHT_500 = 500;

  /**
   * Text opacity.
   */
  static readonly TEXT_OPACITY = 0.6;

  /**
   * Button width.
   */
  static readonly BUTTON_WIDTH = '86.7%';

  /**
   * Library name.
   */
  static readonly LIBRARY_NAME: string = 'entry';

  /**
   * File name.
   */
  static readonly FILE_NAME: string = "/image.yuv";

  /**
   * Yuv xcomponent id.
   */
  static readonly XCOMPONENT_ID: string = 'xcomponent';
}